---
name: ((deployment_name))

releases:
- name: credhub
  version: ((credhub_version))
  sha1: ((credhub_sha1))
  url: https://bosh.io/d/github.com/pivotal-cf/credhub-release?v=((credhub_version))

instance_groups: 
- name: credhub
  instances: 1
  azs: [z1]
  networks: [{name: ((network_name))}]
  stemcell: default
  vm_type: ((credhub_vm_type))
  jobs:
  - name: credhub
    release: credhub
    properties:
      credhub:
        tls: ((credhub_tls))
        authentication:
          uaa:
            url: https://((uaa_host))
            verification_key: ((uaa_jwt_public_key))
            ca_certs: 
            - ((uaa_tls_ca))
        data_storage:
          type: postgres
          username: ((credhub_database_username))
          password: ((credhub_database_password))
          host: ((credhub_database_host))
          port: ((credhub_database_port))
          database: credhub
          require_tls: true
          tls_ca: ((postgres_ca_cert))
        encryption:
          keys: 
          - provider_name: int
            encryption_password: ((credhub_encryption_password))
            active: true
          providers: 
          - name: int
            type: internal

variables:
- name: credhub_encryption_password
  type: password
  options:
    length: 40
- name: credhub-ca
  type: certificate
  options:
    is_ca: true
    common_name: CredHub CA
- name: credhub_tls
  type: certificate
  options:
    ca: credhub-ca
    common_name: ((credhub_host))

stemcells: 
- alias: default 
  os: ubuntu-trusty
  version: latest

update:
  canaries: 1
  max_in_flight: 3
  update_watch_time: 10000-200000
  canary_watch_time: 10000-200000